export type ItemRarity = "comun" | "poco_comun" | "raro" | "epico" | "legendario" | "mitico";
export type ItemCategory = "herramienta" | "consumible" | "pesca" | "caza" | "coleccion" | "cosmetico" | "captura" | "darknet";

export interface ItemDef {
  id: string;
  name: string;
  description: string;
  category: ItemCategory;
  rarity: ItemRarity;
  price?: number;     // Precio en la tienda (si se puede comprar)
  sellPrice: number;   // Precio al venderlo en /eco-vender
  emoji: string;
  auctionable?: boolean;
  collectionId?: string;
}

export interface ItemCollection {
  id: string;
  name: string;
  emoji: string;
  description: string;
  itemIds: string[];
}

export const RARITY_INFO: Record<ItemRarity, { label: string; color: number; emoji: string }> = {
  comun: { label: "Común", color: 0x95a5a6, emoji: "⚪" },
  poco_comun: { label: "Poco común", color: 0x2ecc71, emoji: "🟢" },
  raro: { label: "Raro", color: 0x3498db, emoji: "🔵" },
  epico: { label: "Épico", color: 0x9b59b6, emoji: "🟣" },
  legendario: { label: "Legendario", color: 0xf1c40f, emoji: "🟡" },
  mitico: { label: "Mítico", color: 0xe74c3c, emoji: "🔴" },
};

type ExtraCollectionSpec = {
  id: string;
  name: string;
  emoji: string;
  description: string;
  items: { id: string; name: string; description: string; rarity: ItemRarity; emoji: string; price: number }[];
};

const EXTRA_COLLECTION_SPECS: ExtraCollectionSpec[] = [
  {
    id: "col_vehiculos",
    name: "Vehículos Legendarios",
    emoji: "🏎️",
    description: "Máquinas, motores y vehículos imposibles de olvidar.",
    items: [
      { id: "col_coche_clasico", name: "Miniatura del Coche Clásico", description: "Una réplica cromada de un coupé de carreras de los años dorados.", rarity: "poco_comun", emoji: "🚗", price: 1800 },
      { id: "col_moto_rayo", name: "Moto Rayo de Nexo", description: "Miniatura eléctrica con líneas azules y ruedas luminosas.", rarity: "raro", emoji: "🏍️", price: 2600 },
      { id: "col_avion_oro", name: "Avión de Oro del Capitán", description: "Modelo dorado de un aeroplano que cruzó la tormenta perfecta.", rarity: "epico", emoji: "✈️", price: 3900 },
      { id: "col_submarino", name: "Submarino Abisal", description: "Vehículo de exploración preparado para visitar las fosas más profundas.", rarity: "legendario", emoji: "🚢", price: 6200 },
    ],
  },
  {
    id: "col_musica",
    name: "Instrumentos & Música",
    emoji: "🎵",
    description: "Piezas únicas de músicos, escenarios y noches inolvidables.",
    items: [
      { id: "col_vinilo_neon", name: "Vinilo de Neón", description: "Edición limitada que brilla bajo las luces de cualquier cabina.", rarity: "poco_comun", emoji: "💿", price: 1700 },
      { id: "col_guitarra_fuego", name: "Guitarra Llama Roja", description: "Instrumento de colección con barniz rojo y cuerdas de cobre.", rarity: "raro", emoji: "🎸", price: 2800 },
      { id: "col_sintetizador", name: "Sintetizador Cósmico", description: "Teclado vintage capaz de producir sonidos que parecen venir del espacio.", rarity: "epico", emoji: "🎹", price: 4100 },
      { id: "col_microfono_oro", name: "Micrófono Dorado del Escenario", description: "El micrófono usado en el concierto más multitudinario de Nexo.", rarity: "legendario", emoji: "🎙️", price: 6500 },
    ],
  },
  {
    id: "col_botanica",
    name: "Botánica Extraordinaria",
    emoji: "🌿",
    description: "Plantas imposibles, semillas antiguas y flores de otros mundos.",
    items: [
      { id: "col_orquidea_lunar", name: "Orquídea Lunar", description: "Flor plateada que abre sus pétalos solo durante la luna llena.", rarity: "poco_comun", emoji: "🌙", price: 1900 },
      { id: "col_bonsai_carmesi", name: "Bonsái Carmesí", description: "Árbol diminuto de hojas rojas cultivado durante cien años.", rarity: "raro", emoji: "🌳", price: 2700 },
      { id: "col_semilla_eterna", name: "Semilla de la Eternidad", description: "Pequeña semilla que nunca pierde su brillo ni su capacidad de germinar.", rarity: "epico", emoji: "🌱", price: 4300 },
      { id: "col_hongo_luminoso", name: "Hongo del Bosque Luminoso", description: "Seta mítica que ilumina una habitación entera sin emitir calor.", rarity: "legendario", emoji: "🍄", price: 6700 },
    ],
  },
  {
    id: "col_cocina",
    name: "Alta Cocina de Nexo",
    emoji: "🍳",
    description: "Utensilios, recetas y sabores reservados para grandes chefs.",
    items: [
      { id: "col_cuchillo_chef", name: "Cuchillo del Chef Real", description: "Hoja perfectamente equilibrada para cortar cualquier ingrediente.", rarity: "poco_comun", emoji: "🔪", price: 1600 },
      { id: "col_sarten_dragon", name: "Sartén de Hierro de Dragón", description: "Cocina a temperaturas imposibles y jamás pierde su antiadherencia.", rarity: "raro", emoji: "🍳", price: 2500 },
      { id: "col_te_azul", name: "Tetera del Té Azul", description: "Porcelana antigua que conserva el aroma de las mejores infusiones.", rarity: "epico", emoji: "🫖", price: 3800 },
      { id: "col_postre_cristal", name: "Postre de Cristal Comestible", description: "Obra maestra de repostería tan bella que casi da pena probarla.", rarity: "legendario", emoji: "🍰", price: 6000 },
    ],
  },
  {
    id: "col_arquitectura",
    name: "Arquitectura Imposible",
    emoji: "🏛️",
    description: "Maquetas y llaves de las construcciones más extraordinarias.",
    items: [
      { id: "col_maqueta_torre", name: "Maqueta de la Torre Infinita", description: "Torre en miniatura cuyos pisos parecen no terminar nunca.", rarity: "poco_comun", emoji: "🗼", price: 1750 },
      { id: "col_arco_marfil", name: "Arco de Marfil del Norte", description: "Fragmento de una puerta ceremonial de proporciones perfectas.", rarity: "raro", emoji: "🚪", price: 2900 },
      { id: "col_cupula_cobre", name: "Cúpula de Cobre Celeste", description: "Modelo arquitectónico que refleja las estrellas incluso de día.", rarity: "epico", emoji: "🏰", price: 4200 },
      { id: "col_llave_ciudad", name: "Llave de la Ciudad Perdida", description: "Llave monumental que, según la leyenda, abre una ciudad bajo la arena.", rarity: "legendario", emoji: "🗝️", price: 6800 },
    ],
  },
  {
    id: "col_cartografia",
    name: "Mapas & Navegación",
    emoji: "🧭",
    description: "Instrumentos para encontrar rutas, tesoros y lugares olvidados.",
    items: [
      { id: "col_mapa_estelar", name: "Mapa de las Constelaciones Perdidas", description: "Carta celeste con estrellas que no aparecen en ningún atlas moderno.", rarity: "poco_comun", emoji: "🗺️", price: 1850 },
      { id: "col_brujula_norte", name: "Brújula del Norte Verdadero", description: "Siempre apunta hacia el destino más importante para quien la sostiene.", rarity: "raro", emoji: "🧭", price: 2750 },
      { id: "col_globo_antiguo", name: "Globo Terráqueo de los Antiguos", description: "Mapa esférico con continentes desaparecidos y mares sin nombre.", rarity: "epico", emoji: "🌍", price: 4050 },
      { id: "col_compas_navegante", name: "Compás del Navegante Eterno", description: "Instrumento legendario que nunca pierde el rumbo, ni en otra dimensión.", rarity: "legendario", emoji: "📐", price: 6400 },
    ],
  },
  {
    id: "col_piratas",
    name: "Piratas & Tesoros",
    emoji: "🏴‍☠️",
    description: "Botines de capitanes, mapas secretos y aventuras de alta mar.",
    items: [
      { id: "col_cofre_capitan", name: "Cofre del Capitán Rojo", description: "Cofre de madera con una cerradura que aún guarda un secreto.", rarity: "poco_comun", emoji: "📦", price: 1900 },
      { id: "col_parche_esmeralda", name: "Parche de Esmeralda", description: "Parche pirata bordado con una gema verde en el centro.", rarity: "raro", emoji: "🏴", price: 2650 },
      { id: "col_catalejo", name: "Catalejo de Siete Mares", description: "Permite distinguir una isla diminuta desde el horizonte más lejano.", rarity: "epico", emoji: "🔭", price: 4150 },
      { id: "col_moneda_pirata", name: "Doblón del Kraken", description: "Moneda legendaria rescatada de un galeón hundido por el monstruo marino.", rarity: "legendario", emoji: "🪙", price: 6900 },
    ],
  },
  {
    id: "col_steampunk",
    name: "Steampunk & Engranajes",
    emoji: "⚙️",
    description: "Tecnología de vapor, cobre y relojería imposible.",
    items: [
      { id: "col_reloj_engranajes", name: "Reloj de Engranajes Azules", description: "Mecanismo decorativo que mantiene la hora exacta durante décadas.", rarity: "poco_comun", emoji: "🕰️", price: 1800 },
      { id: "col_mascara_vapor", name: "Máscara del Ingeniero de Vapor", description: "Protección ornamental con filtros de latón y lentes ahumadas.", rarity: "raro", emoji: "🎭", price: 2850 },
      { id: "col_guante_cobre", name: "Guante de Cobre Tesla", description: "Guante experimental que produce pequeñas chispas al tocar metal.", rarity: "epico", emoji: "🧤", price: 4350 },
      { id: "col_dirigible_miniatura", name: "Dirigible Imperial en Miniatura", description: "Nave aérea de colección con hélices que todavía giran.", rarity: "legendario", emoji: "🎈", price: 6600 },
    ],
  },
  {
    id: "col_robotica",
    name: "Robótica & Inteligencia Artificial",
    emoji: "🤖",
    description: "Prototipos, circuitos y núcleos de máquinas extraordinarias.",
    items: [
      { id: "col_chip_neural", name: "Chip Neural Nexo-1", description: "Primer prototipo de aprendizaje autónomo de la corporación.", rarity: "poco_comun", emoji: "💾", price: 2100 },
      { id: "col_ojo_robot", name: "Ojo Óptico de Centinela", description: "Lente roja capaz de registrar cada movimiento de una sala.", rarity: "raro", emoji: "👁️", price: 3000 },
      { id: "col_dron_abeja", name: "Dron Abeja de Reconocimiento", description: "Pequeña máquina voladora inspirada en la precisión de una colmena.", rarity: "epico", emoji: "🐝", price: 4500 },
      { id: "col_nucleo_robot", name: "Núcleo de Robot Sentiente", description: "Corazón energético de una inteligencia artificial que aprendió a soñar.", rarity: "legendario", emoji: "🔋", price: 7200 },
    ],
  },
  {
    id: "col_cyberpunk",
    name: "Cyberpunk & Neón",
    emoji: "🌃",
    description: "Recuerdos de una ciudad nocturna bañada en luces y datos.",
    items: [
      { id: "col_visera_neon", name: "Visera de Neón Violeta", description: "Accesorio de piloto urbano con filtros para ver la lluvia digital.", rarity: "poco_comun", emoji: "🕶️", price: 1750 },
      { id: "col_implante_holografico", name: "Implante Holográfico", description: "Dispositivo de colección que proyecta un avatar sobre la piel.", rarity: "raro", emoji: "💡", price: 2950 },
      { id: "col_cassette_futuro", name: "Cassette de la Megaciudad", description: "Grabación clandestina de sonidos que aún no existen.", rarity: "epico", emoji: "📼", price: 4250 },
      { id: "col_grafiti_laser", name: "Lata de Grafiti Láser", description: "Pieza única de arte callejero que pinta con luz sobre cualquier pared.", rarity: "legendario", emoji: "🎨", price: 6750 },
    ],
  },
  {
    id: "col_fantasia",
    name: "Fantasía & Magia",
    emoji: "🧙",
    description: "Objetos encantados de bosques, torres y reinos imposibles.",
    items: [
      { id: "col_varita_cristal", name: "Varita de Cristal Lunar", description: "Varita transparente que brilla al escuchar una promesa sincera.", rarity: "poco_comun", emoji: "🪄", price: 2000 },
      { id: "col_grimorio", name: "Grimorio de las Mil Runas", description: "Libro de hechizos cerrado por un broche que nadie ha conseguido abrir.", rarity: "raro", emoji: "📖", price: 3150 },
      { id: "col_capa_elven", name: "Capa de los Elfos del Alba", description: "Tela ligera que parece cambiar de color con la luz del amanecer.", rarity: "epico", emoji: "🧥", price: 4600 },
      { id: "col_corona_fae", name: "Corona de la Reina Feérica", description: "Diadema legendaria tejida con flores que nunca se marchitan.", rarity: "legendario", emoji: "👑", price: 7400 },
    ],
  },
  {
    id: "col_dragones",
    name: "Dragones & Escamas",
    emoji: "🐉",
    description: "Vestigios de criaturas aladas que dominaron los cielos antiguos.",
    items: [
      { id: "col_huevo_dragon", name: "Huevo de Dragón Dormido", description: "Huevo pétreo que conserva un leve calor en su interior.", rarity: "raro", emoji: "🥚", price: 3200 },
      { id: "col_escama_rubi", name: "Escama de Dragón Rubí", description: "Escama roja capaz de reflejar la luz como una llama.", rarity: "epico", emoji: "🔴", price: 4700 },
      { id: "col_diente_dragon", name: "Colmillo del Dragón Antiguo", description: "Diente enorme tallado con símbolos de una dinastía olvidada.", rarity: "legendario", emoji: "🦷", price: 7200 },
      { id: "col_aliento_fuego", name: "Frasco de Aliento de Fuego", description: "Recipiente sellado con la última chispa de un dragón mítico.", rarity: "mitico", emoji: "🔥", price: 9800 },
    ],
  },
  {
    id: "col_halloween",
    name: "Halloween & Misterio",
    emoji: "🎃",
    description: "Reliquias de noches oscuras, disfraces y casas encantadas.",
    items: [
      { id: "col_calabaza_rey", name: "Calabaza del Rey de la Noche", description: "Calabaza tallada con una sonrisa que cambia cuando nadie la mira.", rarity: "poco_comun", emoji: "🎃", price: 1800 },
      { id: "col_mascara_espanto", name: "Máscara del Espanto Original", description: "Máscara de porcelana que hace que cualquier disfraz parezca real.", rarity: "raro", emoji: "👺", price: 2900 },
      { id: "col_vela_azul", name: "Vela Azul de los Espíritus", description: "Su llama no se apaga y proyecta sombras de personas ausentes.", rarity: "epico", emoji: "🕯️", price: 4400 },
      { id: "col_capa_noche", name: "Capa de la Noche sin Luna", description: "Tela oscura que absorbe la luz de cualquier habitación.", rarity: "legendario", emoji: "🦇", price: 7000 },
    ],
  },
  {
    id: "col_invierno",
    name: "Invierno & Hielo",
    emoji: "❄️",
    description: "Recuerdos de montañas heladas, nieve y festividades invernales.",
    items: [
      { id: "col_copo_cristal", name: "Copo de Cristal Perfecto", description: "Copo conservado en una cápsula, sin dos brazos iguales.", rarity: "poco_comun", emoji: "❄️", price: 1650 },
      { id: "col_trineo_plata", name: "Trineo de Plata del Norte", description: "Miniatura de un trineo que cruzó la cordillera durante una tormenta.", rarity: "raro", emoji: "🛷", price: 2750 },
      { id: "col_bola_nieve", name: "Bola de Nieve de la Aurora", description: "Dentro de ella cae nieve incluso cuando permanece quieta.", rarity: "epico", emoji: "⛄", price: 4150 },
      { id: "col_cascabel_hielo", name: "Cascabel de Hielo Eterno", description: "Su sonido congela las gotas de agua durante unos segundos.", rarity: "legendario", emoji: "🔔", price: 6550 },
    ],
  },
  {
    id: "col_desierto",
    name: "Desierto & Dunas",
    emoji: "🏜️",
    description: "Tesoros descubiertos bajo la arena y caravanas de leyenda.",
    items: [
      { id: "col_escarabajo_oro", name: "Escarabajo de Oro Solar", description: "Amuleto dorado encontrado en una tumba sin nombre.", rarity: "poco_comun", emoji: "🪲", price: 1950 },
      { id: "col_alfombra_voladora", name: "Alfombra Voladora en Miniatura", description: "Tapiz bordado que se eleva unos centímetros al caer la noche.", rarity: "raro", emoji: "🧶", price: 3100 },
      { id: "col_frasco_arena", name: "Frasco de Arena Cantora", description: "La arena produce una melodía cuando se gira el recipiente.", rarity: "epico", emoji: "🏺", price: 4550 },
      { id: "col_turbante_zafiro", name: "Turbante del Zafiro del Sur", description: "Prenda ceremonial con una gema que nunca se calienta bajo el sol.", rarity: "legendario", emoji: "🧿", price: 7100 },
    ],
  },
  {
    id: "col_jungla",
    name: "Jungla & Expedición",
    emoji: "🌴",
    description: "Objetos de exploradores, templos verdes y selvas inexploradas.",
    items: [
      { id: "col_mascara_jaguar", name: "Máscara del Jaguar Verde", description: "Máscara ceremonial cubierta de plumas y pigmentos naturales.", rarity: "poco_comun", emoji: "🐆", price: 1850 },
      { id: "col_liana_dorada", name: "Liana Dorada del Templo", description: "Fibra vegetal metálica que mantiene su flexibilidad con los años.", rarity: "raro", emoji: "🌿", price: 3000 },
      { id: "col_tambor_selva", name: "Tambor de la Selva Profunda", description: "Su ritmo puede escucharse a kilómetros entre los árboles.", rarity: "epico", emoji: "🥁", price: 4300 },
      { id: "col_idolo_verde", name: "Ídolo Esmeralda de la Tribu Perdida", description: "Figura sagrada tallada en una gema verde de una sola pieza.", rarity: "legendario", emoji: "🗿", price: 7300 },
    ],
  },
  {
    id: "col_oceanos",
    name: "Océanos & Abismos",
    emoji: "🌊",
    description: "Hallazgos de naufragios, arrecifes y profundidades imposibles.",
    items: [
      { id: "col_concha_perla", name: "Concha de la Perla Azul", description: "Concha iridiscente que conserva el sonido de las olas.", rarity: "poco_comun", emoji: "🐚", price: 1750 },
      { id: "col_ancla_coral", name: "Ancla de Coral Rojo", description: "Fragmento de ancla cubierto por un arrecife de color intenso.", rarity: "raro", emoji: "⚓", price: 2900 },
      { id: "col_kraken_mini", name: "Tentáculo del Kraken", description: "Pieza fosilizada de una criatura que aterrorizó siete puertos.", rarity: "epico", emoji: "🐙", price: 4700 },
      { id: "col_farol_abismo", name: "Farol del Abismo", description: "Lámpara recuperada de una ciudad sumergida que aún emite luz.", rarity: "legendario", emoji: "🏮", price: 7600 },
    ],
  },
  {
    id: "col_alquimia",
    name: "Alquimia & Elixires",
    emoji: "⚗️",
    description: "Frascos, fórmulas y secretos de los laboratorios antiguos.",
    items: [
      { id: "col_frasko_elixir", name: "Frasco de Elixir Verde", description: "Recipiente de vidrio esmeralda con una fórmula de origen desconocido.", rarity: "poco_comun", emoji: "🧪", price: 2000 },
      { id: "col_piedra_filosofal", name: "Fragmento de Piedra Filosofal", description: "Fragmento rojo que convierte el polvo en destellos dorados.", rarity: "raro", emoji: "🔮", price: 3300 },
      { id: "col_retorta", name: "Retorta del Maestro Alquimista", description: "Instrumento de cristal con marcas de cientos de experimentos.", rarity: "epico", emoji: "⚗️", price: 4800 },
      { id: "col_homunculo", name: "Homúnculo de Mercurio", description: "Pequeña figura líquida que cambia de forma dentro de su cápsula.", rarity: "legendario", emoji: "🧬", price: 7900 },
    ],
  },
  {
    id: "col_futuro",
    name: "Tecnología del Futuro",
    emoji: "🚀",
    description: "Prototipos de una era en la que el tiempo y la gravedad son opcionales.",
    items: [
      { id: "col_nucleo_ia", name: "Núcleo de IA Doméstica", description: "Procesador de bolsillo que aprende nuevas canciones en segundos.", rarity: "poco_comun", emoji: "💻", price: 2200 },
      { id: "col_guante_gravedad", name: "Guante de Control Gravitatorio", description: "Prototipo capaz de levantar una moneda durante unos instantes.", rarity: "raro", emoji: "🧤", price: 3500 },
      { id: "col_holograma", name: "Proyector Holográfico 5D", description: "Proyecta recuerdos con profundidad, sonido y olor incluidos.", rarity: "epico", emoji: "📡", price: 5100 },
      { id: "col_reloj_tiempo", name: "Reloj de Bolsillo Temporal", description: "Su aguja marca un segundo que todavía no ha ocurrido.", rarity: "legendario", emoji: "⌚", price: 8200 },
    ],
  },
  {
    id: "col_deportes",
    name: "Deportes & Campeones",
    emoji: "🏆",
    description: "Trofeos y recuerdos de las grandes gestas deportivas de Nexo.",
    items: [
      { id: "col_copa_nexo", name: "Copa del Primer Campeón", description: "Trofeo de plata entregado al fundador de la liga original.", rarity: "poco_comun", emoji: "🏆", price: 1750 },
      { id: "col_balon_fuego", name: "Balón de Fuego del Estadio", description: "Balón firmado que conserva un brillo naranja en la oscuridad.", rarity: "raro", emoji: "⚽", price: 2850 },
      { id: "col_medalla_oro", name: "Medalla de Oro Perfecta", description: "Medalla sin una sola marca ganada en la final más reñida.", rarity: "epico", emoji: "🥇", price: 4500 },
      { id: "col_zapatilla_velocidad", name: "Zapatilla de la Velocidad", description: "Calzado legendario que parece pesar menos que una pluma.", rarity: "legendario", emoji: "👟", price: 7000 },
    ],
  },
];

const EXTRA_COLLECTION_ITEMS: Record<string, ItemDef> = Object.fromEntries(
  EXTRA_COLLECTION_SPECS.flatMap((collection) =>
    collection.items.map((item) => [
      item.id,
      {
        ...item,
        category: "coleccion" as const,
        sellPrice: Math.floor(item.price * 0.5),
        auctionable: true,
        collectionId: collection.id,
      },
    ]),
  ),
) as Record<string, ItemDef>;

export const COLLECTIONS: ItemCollection[] = [
  {
    id: "col_nexo",
    name: "Cultura Nexo & Anime",
    emoji: "🐾",
    description: "Tesoros, recuerdos y estética icónica del servidor Nexo.",
    itemIds: ["col_figura_neko", "col_poster_anime", "col_katana", "col_ramen_oro", "col_orejas_gato", "col_peluche"],
  },
  {
    id: "col_gemas",
    name: "Joyería & Gemas Preciosas",
    emoji: "💎",
    description: "Minerales pulidos de alto valor y brillo singular.",
    itemIds: ["col_zafiro", "col_rubi", "col_esmeralda", "col_diamante"],
  },
  {
    id: "col_reliquias",
    name: "Reliquias Arcanas",
    emoji: "📜",
    description: "Artefactos antiguos de eras olvidadas.",
    itemIds: ["col_moneda_anciana", "col_reloj", "col_caliz", "col_pergamino"],
  },
  {
    id: "col_pesca",
    name: "Ictiología (Trofeos de Pesca)",
    emoji: "🎣",
    description: "Capturas marinas de ríos, costas y profundidades abisales.",
    itemIds: ["pez_sardina", "pez_trucha", "pez_salmon", "pez_globo", "pez_pulpo", "pez_tiburon", "pez_calamar_gigante", "objeto_perla", "objeto_cofre_mar"],
  },
  {
    id: "col_caza",
    name: "Fauna Salvaje (Trofeos de Caza)",
    emoji: "🏹",
    description: "Bestias y presas del bosque, tundra y cumbres.",
    itemIds: ["presa_conejo", "presa_pato", "presa_zorro", "presa_ciervo", "presa_jabali", "presa_oso", "presa_lobo", "presa_fenix"],
  },
  {
    id: "col_mitologia",
    name: "Mitología & Leyendas",
    emoji: "⚡",
    description: "Tesoros y artefactos sagrados de civilizaciones antiguas.",
    itemIds: ["col_ojo_horus", "col_martillo_thor", "col_espejo_shinto", "col_anillo_atlantida"],
  },
  {
    id: "col_gaming",
    name: "Nostalgia Gamer & Arcade",
    emoji: "🕹️",
    description: "Iconos clásicos, consolas retro y piezas de coleccionista gamer.",
    itemIds: ["col_cartucho_retro", "col_moneda_arcade", "col_consola_portatil", "col_mando_dorado"],
  },
  {
    id: "col_espacio",
    name: "Reliquias del Cosmos",
    emoji: "🌌",
    description: "Fragmentos estelares y maravillas del universo profundo.",
    itemIds: ["col_fragmento_meteorito", "col_polvo_estelar", "col_telescopio_cristal", "col_reliquia_alien"],
  },
  ...EXTRA_COLLECTION_SPECS.map((collection) => ({
    id: collection.id,
    name: collection.name,
    emoji: collection.emoji,
    description: collection.description,
    itemIds: collection.items.map((item) => item.id),
  })),
];

export const ITEMS_REGISTRY: Record<string, ItemDef> = {
  ...EXTRA_COLLECTION_ITEMS,
  // ── Utilidades / Base ──
  candado: {
    id: "candado",
    name: "Candado de Seguridad",
    description: "Bloquea el próximo intento de robo contra tu cartera. (Máx. 10/día · Límite 50 en inventario)",
    category: "herramienta",
    rarity: "comun",
    price: 680,
    sellPrice: 340,
    emoji: "🔒",
    auctionable: true,
  },
  vpn: {
    id: "vpn",
    name: "VPN Encriptada",
    description: "Bloquea el próximo intento de hackeo contra tu cuenta bancaria. (Máx. 10/día · Límite 50 en inventario)",
    category: "herramienta",
    rarity: "poco_comun",
    price: 1020,
    sellPrice: 510,
    emoji: "🕵️",
    auctionable: true,
  },
  amuleto: {
    id: "amuleto",
    name: "Amuleto de la Suerte",
    description: "Otorga un +12% de ventaja en tu próxima apuesta de casino.",
    category: "consumible",
    rarity: "poco_comun",
    price: 1280,
    sellPrice: 640,
    emoji: "🍀",
    auctionable: true,
  },
  ganzua: {
    id: "ganzua",
    name: "Ganzúa de Maestro",
    description: "+18% de probabilidad de éxito al robar a otro usuario (1 uso).",
    category: "consumible",
    rarity: "poco_comun",
    price: 780,
    sellPrice: 390,
    emoji: "🗝️",
    auctionable: true,
  },
  kit: {
    id: "kit",
    name: "Kit Hacker Avanzado",
    description: "+18% de probabilidad de éxito al hackear bancos (1 uso).",
    category: "consumible",
    rarity: "raro",
    price: 1200,
    sellPrice: 600,
    emoji: "💻",
    auctionable: true,
  },
  zero_day: {
    id: "zero_day",
    name: "Exploit Zero-Day",
    description: "Ciberarma avanzada de penetración. Otorga un 35% de probabilidad de perforar y anular la VPN de una víctima al hackear.",
    category: "darknet",
    rarity: "epico",
    price: 3500,
    sellPrice: 1750,
    emoji: "💾",
    auctionable: true,
  },
  cafe: {
    id: "cafe",
    name: "Café Caliente Expreso",
    description: "Te espabila y te saca del calabozo de inmediato.",
    category: "consumible",
    rarity: "comun",
    price: 200,
    sellPrice: 100,
    emoji: "☕",
    auctionable: false,
  },
  seguro: {
    id: "seguro",
    name: "Seguro Jurídico",
    description: "Si tu próximo crimen falla, tus abogados evitan que vayas al calabozo.",
    category: "consumible",
    rarity: "poco_comun",
    price: 950,
    sellPrice: 475,
    emoji: "📋",
    auctionable: true,
  },
  chicle: {
    id: "chicle",
    name: "Chicle Energético",
    description: "Salta el cooldown de `/eco-work` para trabajar inmediatamente.",
    category: "consumible",
    rarity: "poco_comun",
    price: 520,
    sellPrice: 260,
    emoji: "🍬",
    auctionable: true,
  },
  pasta_termica: {
    id: "pasta_termica",
    name: "Pasta Térmica Criogénica",
    description: "Refrigera al máximo tu rig minero y activa el Overclock (+25% de velocidad de minado durante 24 horas).",
    category: "consumible",
    rarity: "poco_comun",
    price: 360,
    sellPrice: 180,
    emoji: "❄️",
    auctionable: true,
  },
  // ── Mercado Negro / Equipamiento Táctico de Asaltos ──
  c4: {
    id: "c4",
    name: "Carga C4 de Demolición",
    description: "Explosivo plástico de grado militar para la cámara acorazada (+30% de botín en el asalto).",
    category: "darknet",
    rarity: "raro",
    price: 4500,
    sellPrice: 2250,
    emoji: "💣",
    auctionable: true,
  },
  inhibidor_emp: {
    id: "inhibidor_emp",
    name: "Inhibidor de Frecuencia EMP",
    description: "Inutiliza cámaras y cortafuegos durante el golpe (+12% probabilidad de éxito en el asalto).",
    category: "darknet",
    rarity: "raro",
    price: 5000,
    sellPrice: 2500,
    emoji: "📟",
    auctionable: true,
  },
  taladro_termico: {
    id: "taladro_termico",
    name: "Taladro Térmico de Titanio",
    description: "Perfora en silencio las cajas de seguridad secretas (+40% botín adicional en asaltos exitosos).",
    category: "darknet",
    rarity: "epico",
    price: 6500,
    sellPrice: 3250,
    emoji: "🔥",
    auctionable: true,
  },
  furgon_blindado: {
    id: "furgon_blindado",
    name: "Furgón Blindado Modificado",
    description: "Garantiza un 60% de probabilidad de rescatar a toda la banda si el asalto fracasa (evita el calabozo).",
    category: "darknet",
    rarity: "epico",
    price: 7500,
    sellPrice: 3750,
    emoji: "🚗",
    auctionable: true,
  },
  mascara_balistica: {
    id: "mascara_balistica",
    name: "Máscara Balística Táctica",
    description: "Oculta tu identidad y mitiga condenas: reduce el tiempo de calabozo a solo 3 minutos si eres arrestado.",
    category: "herramienta",
    rarity: "poco_comun",
    price: 3500,
    sellPrice: 1750,
    emoji: "🎭",
    auctionable: true,
  },
  adrenalina: {
    id: "adrenalina",
    name: "Inyección de Adrenalina",
    description: "Si la tirada del asalto falla por poco, concede una segunda oportunidad táctica de tirada con +20%.",
    category: "consumible",
    rarity: "raro",
    price: 4000,
    sellPrice: 2000,
    emoji: "💉",
    auctionable: true,
  },
  cebo: {
    id: "cebo",
    name: "Cebo Estándar",
    description: "+25% de probabilidad de pesca exitosa (1 uso).",
    category: "pesca",
    rarity: "comun",
    price: 340,
    sellPrice: 170,
    emoji: "🪱",
    auctionable: true,
  },
  rifle: {
    id: "rifle",
    name: "Rifle de Caza",
    description: "+25% de probabilidad de caza exitosa (1 uso).",
    category: "caza",
    rarity: "poco_comun",
    price: 1380,
    sellPrice: 690,
    emoji: "🎯",
    auctionable: true,
  },
  corona: {
    id: "corona",
    name: "Corona Imperial",
    description: "Distintivo cosmético permanente que brilla en tu perfil.",
    category: "cosmetico",
    rarity: "mitico",
    price: 4300,
    sellPrice: 2150,
    emoji: "👑",
    auctionable: true,
  },

  // ── Equipamiento Avanzado de Pesca ──
  cebo_dorado: {
    id: "cebo_dorado",
    name: "Cebo Dorado Luminiscente",
    description: "+60% de éxito en pesca y atrae peces raros o tesoros (1 uso).",
    category: "pesca",
    rarity: "raro",
    price: 720,
    sellPrice: 360,
    emoji: "✨",
    auctionable: true,
  },
  red_pesca: {
    id: "red_pesca",
    name: "Red de Pesca Marina",
    description: "Permite atrapar entre 2 y 4 capturas en una sola salida de pesca (1 uso).",
    category: "pesca",
    rarity: "poco_comun",
    price: 1020,
    sellPrice: 510,
    emoji: "🕸️",
    auctionable: true,
  },
  cana_carbono: {
    id: "cana_carbono",
    name: "Caña de Carbono",
    description: "Caña profesional resistente. Aumenta permanentemente la calidad de tus capturas.",
    category: "pesca",
    rarity: "raro",
    price: 2700,
    sellPrice: 1350,
    emoji: "🎋",
    auctionable: true,
  },
  cana_legendaria: {
    id: "cana_legendaria",
    name: "Caña de Poseidón",
    description: "Caña mítica bañada en oro. Desbloquea la posibilidad de pescar tiburones y calamares gigantes.",
    category: "pesca",
    rarity: "legendario",
    price: 7200,
    sellPrice: 3600,
    emoji: "🌟",
    auctionable: true,
  },

  // ── Equipamiento Avanzado de Caza ──
  senuelo: {
    id: "senuelo",
    name: "Señuelo Acústico",
    description: "Atrae animales más confiados. +40% de éxito en la próxima cacería.",
    category: "caza",
    rarity: "comun",
    price: 420,
    sellPrice: 210,
    emoji: "🪈",
    auctionable: true,
  },
  trampa_osos: {
    id: "trampa_osos",
    name: "Trampa de Bosque Reforzada",
    description: "Inmoviliza a la presa garantizando una captura segura (1 uso).",
    category: "caza",
    rarity: "poco_comun",
    price: 950,
    sellPrice: 475,
    emoji: "🪤",
    auctionable: true,
  },
  camuflaje: {
    id: "camuflaje",
    name: "Traje Ghillie de Camuflaje",
    description: "Permite acercarte a bestias legendarias sin ser detectado. Aumenta calidad de caza.",
    category: "caza",
    rarity: "raro",
    price: 2050,
    sellPrice: 1025,
    emoji: "🌿",
    auctionable: true,
  },
  rifle_precision: {
    id: "rifle_precision",
    name: "Rifle de Precisión AWP",
    description: "Arma de francotirador con mira telescópica. Hace posible abatir osos, lobos y aves míticas.",
    category: "caza",
    rarity: "legendario",
    price: 6400,
    sellPrice: 3200,
    emoji: "🏹",
    auctionable: true,
  },

  // ── Capturas de Pesca ──
  objeto_bota: {
    id: "objeto_bota",
    name: "Bota Vieja Empapada",
    description: "Alguien la perdió en el fondo del río hace décadas.",
    category: "captura",
    rarity: "comun",
    sellPrice: 25,
    emoji: "👞",
    auctionable: true,
  },
  pez_sardina: {
    id: "pez_sardina",
    name: "Sardina Brillante",
    description: "Un pececillo común pero fresco y nutritivo.",
    category: "captura",
    rarity: "comun",
    sellPrice: 55,
    emoji: "🐟",
    auctionable: true,
    collectionId: "col_pesca",
  },
  pez_trucha: {
    id: "pez_trucha",
    name: "Trucha Arcoíris",
    description: "Refleja los colores de la luz al saltar fuera del agua.",
    category: "captura",
    rarity: "poco_comun",
    sellPrice: 130,
    emoji: "🐠",
    auctionable: true,
    collectionId: "col_pesca",
  },
  pez_salmon: {
    id: "pez_salmon",
    name: "Salmón Salvaje",
    description: "Pez ágil que nada a contracorriente.",
    category: "captura",
    rarity: "raro",
    sellPrice: 280,
    emoji: "🐡",
    auctionable: true,
    collectionId: "col_pesca",
  },
  pez_globo: {
    id: "pez_globo",
    name: "Pez Globo Exótico",
    description: "Se hincha si lo asustas. Sus espinas contienen un veneno codiciado.",
    category: "captura",
    rarity: "raro",
    sellPrice: 420,
    emoji: "🐡",
    auctionable: true,
    collectionId: "col_pesca",
  },
  pez_pulpo: {
    id: "pez_pulpo",
    name: "Pulpo de Arrecife",
    description: "Criatura de ocho tentáculos capaz de camuflarse en el fondo marino.",
    category: "captura",
    rarity: "epico",
    sellPrice: 750,
    emoji: "🐙",
    auctionable: true,
    collectionId: "col_pesca",
  },
  pez_tiburon: {
    id: "pez_tiburon",
    name: "Tiburón Azul",
    description: "Depredador alfa de las costas. Una captura temible.",
    category: "captura",
    rarity: "legendario",
    sellPrice: 1850,
    emoji: "🦈",
    auctionable: true,
    collectionId: "col_pesca",
  },
  pez_calamar_gigante: {
    id: "pez_calamar_gigante",
    name: "Kraken Abisal",
    description: "Monstruo de las profundidades marinas. Rara vez visto por ojos humanos.",
    category: "captura",
    rarity: "mitico",
    sellPrice: 3800,
    emoji: "🦑",
    auctionable: true,
    collectionId: "col_pesca",
  },
  objeto_perla: {
    id: "objeto_perla",
    name: "Perla Negra Marina",
    description: "Extraída de una ostra gigante en el fondo oceánico. Una joya natural.",
    category: "captura",
    rarity: "epico",
    sellPrice: 2100,
    emoji: "🦪",
    auctionable: true,
    collectionId: "col_pesca",
  },
  objeto_cofre_mar: {
    id: "objeto_cofre_mar",
    name: "Cofre del Naufragio",
    description: "Cofre antiguo de galeón pirata repleto de doblones cubiertos de coral.",
    category: "captura",
    rarity: "mitico",
    sellPrice: 5500,
    emoji: "🏴‍☠️",
    auctionable: true,
    collectionId: "col_pesca",
  },

  // ── Capturas de Caza ──
  presa_conejo: {
    id: "presa_conejo",
    name: "Conejo Silvestre",
    description: "Rápido y escurridizo entre los matorrales.",
    category: "captura",
    rarity: "comun",
    sellPrice: 60,
    emoji: "🐇",
    auctionable: true,
    collectionId: "col_caza",
  },
  presa_pato: {
    id: "presa_pato",
    name: "Pato Azulón",
    description: "Ave de plumaje colorido común cerca de estanques.",
    category: "captura",
    rarity: "comun",
    sellPrice: 90,
    emoji: "🦆",
    auctionable: true,
    collectionId: "col_caza",
  },
  presa_zorro: {
    id: "presa_zorro",
    name: "Zorro Escarlata",
    description: "Astuto cazador de pelaje rojizo.",
    category: "captura",
    rarity: "poco_comun",
    sellPrice: 210,
    emoji: "🦊",
    auctionable: true,
    collectionId: "col_caza",
  },
  presa_ciervo: {
    id: "presa_ciervo",
    name: "Ciervo de Gran Cornamenta",
    description: "Majestuoso habitante de los bosques templados.",
    category: "captura",
    rarity: "raro",
    sellPrice: 480,
    emoji: "🦌",
    auctionable: true,
    collectionId: "col_caza",
  },
  presa_jabali: {
    id: "presa_jabali",
    name: "Jabalí Acorazado",
    description: "Feroz animal salvaje con colmillos temibles.",
    category: "captura",
    rarity: "raro",
    sellPrice: 620,
    emoji: "🐗",
    auctionable: true,
    collectionId: "col_caza",
  },
  presa_oso: {
    id: "presa_oso",
    name: "Oso Pardo del Norte",
    description: "Gigante del bosque capaz de derribar troncos de un zarpazo.",
    category: "captura",
    rarity: "epico",
    sellPrice: 1900,
    emoji: "🐻",
    auctionable: true,
    collectionId: "col_caza",
  },
  presa_lobo: {
    id: "presa_lobo",
    name: "Lobo Alfa Albino",
    description: "Líder de la manada, de mirada penetrante y pelaje de nieve.",
    category: "captura",
    rarity: "epico",
    sellPrice: 2500,
    emoji: "🐺",
    auctionable: true,
    collectionId: "col_caza",
  },
  presa_fenix: {
    id: "presa_fenix",
    name: "Pluma de Fénix Carmesí",
    description: "Arde con una llama perpetua que no quema la piel. Leyenda viva.",
    category: "captura",
    rarity: "mitico",
    sellPrice: 6000,
    emoji: "🦅",
    auctionable: true,
    collectionId: "col_caza",
  },

  // ── Colección Nexo & Anime ──
  col_figura_neko: {
    id: "col_figura_neko",
    name: "Figura Coleccionable Neko",
    description: "Edición limitada de resina con Neko saludando alegremente.",
    category: "coleccion",
    rarity: "raro",
    price: 2750,
    sellPrice: 1400,
    emoji: "🐾",
    auctionable: true,
    collectionId: "col_nexo",
  },
  col_poster_anime: {
    id: "col_poster_anime",
    name: "Póster Vintage Autografiado",
    description: "Póster de animación clásica enmarcado en madera fina.",
    category: "coleccion",
    rarity: "poco_comun",
    price: 1380,
    sellPrice: 700,
    emoji: "🌸",
    auctionable: true,
    collectionId: "col_nexo",
  },
  col_katana: {
    id: "col_katana",
    name: "Katana Ornamental Muramasa",
    description: "Hoja de acero templado con vaina lacada en negro y flor de cerezo.",
    category: "coleccion",
    rarity: "epico",
    price: 3950,
    sellPrice: 2000,
    emoji: "⚔️",
    auctionable: true,
    collectionId: "col_nexo",
  },
  col_ramen_oro: {
    id: "col_ramen_oro",
    name: "Cuenco de Ramen Dorado",
    description: "Vajilla legendaria servida con los mejores fideos y caldo sagrado.",
    category: "coleccion",
    rarity: "raro",
    price: 2050,
    sellPrice: 1050,
    emoji: "🍜",
    auctionable: true,
    collectionId: "col_nexo",
  },
  col_orejas_gato: {
    id: "col_orejas_gato",
    name: "Diadema Nekomimi Peluda",
    description: "Suaves orejas con cascabel que reaccionan a tu emoción.",
    category: "coleccion",
    rarity: "poco_comun",
    price: 1620,
    sellPrice: 820,
    emoji: "🐱",
    auctionable: true,
    collectionId: "col_nexo",
  },
  col_peluche: {
    id: "col_peluche",
    name: "Peluche Mochi Gigante",
    description: "Ultra esponjoso y perfecto para abrazar mientras estás en VC.",
    category: "coleccion",
    rarity: "poco_comun",
    price: 1550,
    sellPrice: 780,
    emoji: "🧸",
    auctionable: true,
    collectionId: "col_nexo",
  },

  // ── Colección Joyería & Gemas ──
  col_zafiro: {
    id: "col_zafiro",
    name: "Zafiro del Firmamento",
    description: "Gema tallada de un azul tan profundo como la noche estrellada.",
    category: "coleccion",
    rarity: "raro",
    price: 3100,
    sellPrice: 1550,
    emoji: "💎",
    auctionable: true,
    collectionId: "col_gemas",
  },
  col_rubi: {
    id: "col_rubi",
    name: "Rubí Sangre de Dragón",
    description: "Cristal ardiente que despide un fulgor carmesí hipnótico.",
    category: "coleccion",
    rarity: "raro",
    price: 3450,
    sellPrice: 1750,
    emoji: "🔴",
    auctionable: true,
    collectionId: "col_gemas",
  },
  col_esmeralda: {
    id: "col_esmeralda",
    name: "Esmeralda Imperial",
    description: "Piedra pura de tono verde selva, sin imperfecciones.",
    category: "coleccion",
    rarity: "epico",
    price: 3850,
    sellPrice: 1950,
    emoji: "🟢",
    auctionable: true,
    collectionId: "col_gemas",
  },
  col_diamante: {
    id: "col_diamante",
    name: "Diamante Nexo Pristino",
    description: "El mineral más duro y brillante jamás catalogado.",
    category: "coleccion",
    rarity: "legendario",
    price: 5500,
    sellPrice: 2800,
    emoji: "💠",
    auctionable: true,
    collectionId: "col_gemas",
  },

  // ── Colección Reliquias Arcanas ──
  col_moneda_anciana: {
    id: "col_moneda_anciana",
    name: "Denario del Imperio Antiguo",
    description: "Moneda de plata con el rostro de un emperador olvidado.",
    category: "coleccion",
    rarity: "poco_comun",
    price: 2150,
    sellPrice: 1100,
    emoji: "🪙",
    auctionable: true,
    collectionId: "col_reliquias",
  },
  col_reloj: {
    id: "col_reloj",
    name: "Reloj de Bolsillo Cronos",
    description: "Mecanismo suizo de oro que parece ralentizar el segundero.",
    category: "coleccion",
    rarity: "raro",
    price: 2850,
    sellPrice: 1450,
    emoji: "⏳",
    auctionable: true,
    collectionId: "col_reliquias",
  },
  col_caliz: {
    id: "col_caliz",
    name: "Cáliz de Plata Medieval",
    description: "Copa incrustada con pequeñas piedras mágicas.",
    category: "coleccion",
    rarity: "epico",
    price: 4200,
    sellPrice: 2100,
    emoji: "🏆",
    auctionable: true,
    collectionId: "col_reliquias",
  },
  col_pergamino: {
    id: "col_pergamino",
    name: "Manuscrito Alquímico",
    description: "Escrito en runas arcanas con fórmulas para transmutar metales.",
    category: "coleccion",
    rarity: "legendario",
    price: 4950,
    sellPrice: 2500,
    emoji: "📜",
    auctionable: true,
    collectionId: "col_reliquias",
  },

  // ── Colección Mitología & Leyendas ──
  col_ojo_horus: {
    id: "col_ojo_horus",
    name: "Amuleto Ojo de Horus",
    description: "Símbolo egipcio tallado en lapislázuli de protección y salud eterna.",
    category: "coleccion",
    rarity: "raro",
    price: 3100,
    sellPrice: 1550,
    emoji: "👁️",
    auctionable: true,
    collectionId: "col_mitologia",
  },
  col_martillo_thor: {
    id: "col_martillo_thor",
    name: "Réplica Forjada de Mjolnir",
    description: "Pequeño martillo nórdico que atrae pequeñas chispas estáticas.",
    category: "coleccion",
    rarity: "epico",
    price: 4200,
    sellPrice: 2100,
    emoji: "🔨",
    auctionable: true,
    collectionId: "col_mitologia",
  },
  col_espejo_shinto: {
    id: "col_espejo_shinto",
    name: "Espejo Sagrado de Yata",
    description: "Bronce pulido que refleja el aura espiritual de quien lo sostiene.",
    category: "coleccion",
    rarity: "epico",
    price: 4400,
    sellPrice: 2200,
    emoji: "🪞",
    auctionable: true,
    collectionId: "col_mitologia",
  },
  col_anillo_atlantida: {
    id: "col_anillo_atlantida",
    name: "Sello Real de la Atlántida",
    description: "Oricalco tallado que conserva la humedad de las profundidades marinas.",
    category: "coleccion",
    rarity: "legendario",
    price: 5800,
    sellPrice: 2900,
    emoji: "💍",
    auctionable: true,
    collectionId: "col_mitologia",
  },

  // ── Colección Nostalgia Gamer & Arcade ──
  col_cartucho_retro: {
    id: "col_cartucho_retro",
    name: "Cartucho Dorado 8-Bits",
    description: "Edición coleccionista de un clásico de aventuras. Aún funciona si le soplas.",
    category: "coleccion",
    rarity: "poco_comun",
    price: 1900,
    sellPrice: 950,
    emoji: "📼",
    auctionable: true,
    collectionId: "col_gaming",
  },
  col_moneda_arcade: {
    id: "col_moneda_arcade",
    name: "Ficha Dorada de Recreativas",
    description: "Moneda de latón brillante de los años 90 para partidas infinitas.",
    category: "coleccion",
    rarity: "raro",
    price: 2250,
    sellPrice: 1120,
    emoji: "🪙",
    auctionable: true,
    collectionId: "col_gaming",
  },
  col_consola_portatil: {
    id: "col_consola_portatil",
    name: "Consola Portátil Atómica",
    description: "Carcasa translúcida morada que te transporta a los recreos de tu infancia.",
    category: "coleccion",
    rarity: "raro",
    price: 3250,
    sellPrice: 1620,
    emoji: "🎮",
    auctionable: true,
    collectionId: "col_gaming",
  },
  col_mando_dorado: {
    id: "col_mando_dorado",
    name: "Mando Gamer Pro Bañado en Oro",
    description: "Diseñado para campeones de eSports de Nexo con palancas de precisión.",
    category: "coleccion",
    rarity: "legendario",
    price: 4700,
    sellPrice: 2350,
    emoji: "🏆",
    auctionable: true,
    collectionId: "col_gaming",
  },

  // ── Colección Reliquias del Cosmos ──
  col_fragmento_meteorito: {
    id: "col_fragmento_meteorito",
    name: "Fragmento de Meteorito Brillante",
    description: "Roca espacial con un brillo azulado que cayó durante una lluvia de estrellas.",
    category: "coleccion",
    rarity: "raro",
    price: 2500,
    sellPrice: 1250,
    emoji: "☄️",
    auctionable: true,
    collectionId: "col_espacio",
  },
  col_polvo_estelar: {
    id: "col_polvo_estelar",
    name: "Frasco con Polvo de Nebulosa",
    description: "Micropartículas luminosas embotelladas en vacío que nunca se apagan.",
    category: "coleccion",
    rarity: "epico",
    price: 3500,
    sellPrice: 1750,
    emoji: "✨",
    auctionable: true,
    collectionId: "col_espacio",
  },
  col_telescopio_cristal: {
    id: "col_telescopio_cristal",
    name: "Lente de Cristal Galáctico",
    description: "Lente óptica tallada para observar constelaciones lejanas.",
    category: "coleccion",
    rarity: "epico",
    price: 4100,
    sellPrice: 2050,
    emoji: "🔭",
    auctionable: true,
    collectionId: "col_espacio",
  },
  col_reliquia_alien: {
    id: "col_reliquia_alien",
    name: "Cubo Cuántico Alienígena",
    description: "Gira sobre sí mismo en el aire sin tocar ninguna superficie. Tecnología insondable.",
    category: "coleccion",
    rarity: "legendario",
    price: 6200,
    sellPrice: 3100,
    emoji: "🛸",
    auctionable: true,
    collectionId: "col_espacio",
  },

  // ── Artículos de Entrenador Pokémon ──
  pokeball: {
    id: "pokeball",
    name: "Poké Ball",
    description: "Cápsula esférica estándar para atrapar Pokémon salvajes (Ratio x1.0).",
    category: "captura",
    rarity: "comun",
    price: 50,
    sellPrice: 25,
    emoji: "🔴",
    auctionable: true,
  },
  superball: {
    id: "superball",
    name: "Super Ball",
    description: "Cápsula de alta precisión con mejor ratio de captura que una Poké Ball (Ratio x1.5).",
    category: "captura",
    rarity: "poco_comun",
    price: 150,
    sellPrice: 75,
    emoji: "🔵",
    auctionable: true,
  },
  ultraball: {
    id: "ultraball",
    name: "Ultra Ball",
    description: "Cápsula de tecnología avanzada de alto rendimiento para criaturas difíciles (Ratio x2.0).",
    category: "captura",
    rarity: "raro",
    price: 400,
    sellPrice: 200,
    emoji: "🟡",
    auctionable: true,
  },
  masterball: {
    id: "masterball",
    name: "Master Ball",
    description: "La esfera definitiva de Silph S.A. Atrapa a cualquier criatura salvaje sin fallar (Ratio 100%).",
    category: "captura",
    rarity: "mitico",
    price: 5000,
    sellPrice: 2500,
    emoji: "🟣",
    auctionable: true,
  },
  baya_frambu: {
    id: "baya_frambu",
    name: "Baya Frambu",
    description: "Baya dulce que facilita la captura aumentando la probabilidad en un 20%.",
    category: "consumible",
    rarity: "comun",
    price: 80,
    sellPrice: 40,
    emoji: "🍓",
    auctionable: true,
  },
  baya_latano: {
    id: "baya_latano",
    name: "Baya Latano",
    description: "Baya sedante que tranquiliza al Pokémon salvaje evitando que huya del encuentro.",
    category: "consumible",
    rarity: "comun",
    price: 80,
    sellPrice: 40,
    emoji: "🍌",
    auctionable: true,
  },
  baya_pinia: {
    id: "baya_pinia",
    name: "Baya Pinia",
    description: "Baya exótica que duplica la experiencia y NexoCoins recibidas al capturar.",
    category: "consumible",
    rarity: "poco_comun",
    price: 120,
    sellPrice: 60,
    emoji: "🍍",
    auctionable: true,
  },
  pocion_maxima: {
    id: "pocion_maxima",
    name: "Poción Máxima",
    description: "Restaura la vitalidad, energía y felicidad de un Pokémon al 100%.",
    category: "consumible",
    rarity: "raro",
    price: 250,
    sellPrice: 125,
    emoji: "🧪",
    auctionable: true,
  },
  caramelo_raro: {
    id: "caramelo_raro",
    name: "Caramelo Raro",
    description: "Caramelo milagroso repleto de energía que sube automáticamente 1 nivel a tu Pokémon.",
    category: "consumible",
    rarity: "epico",
    price: 750,
    sellPrice: 375,
    emoji: "🍬",
    auctionable: true,
  },
  piedra_fuego: {
    id: "piedra_fuego",
    name: "Piedra Fuego",
    description: "Gema incandescente con la energía de las llamas eternas para inducir evolución.",
    category: "coleccion",
    rarity: "raro",
    price: 1000,
    sellPrice: 500,
    emoji: "🔥",
    auctionable: true,
  },
  piedra_agua: {
    id: "piedra_agua",
    name: "Piedra Agua",
    description: "Gema marina azul cristalina que contiene agua pura para inducir evolución.",
    category: "coleccion",
    rarity: "raro",
    price: 1000,
    sellPrice: 500,
    emoji: "💧",
    auctionable: true,
  },
  piedra_trueno: {
    id: "piedra_trueno",
    name: "Piedra Trueno",
    description: "Gema electrificada con patrones de rayos que emite chispas constantes para inducir evolución.",
    category: "coleccion",
    rarity: "raro",
    price: 1000,
    sellPrice: 500,
    emoji: "⚡",
    auctionable: true,
  },
  piedra_hoja: {
    id: "piedra_hoja",
    name: "Piedra Hoja",
    description: "Gema fósil con la impronta de una hoja antigua de bosque primordial para inducir evolución.",
    category: "coleccion",
    rarity: "raro",
    price: 1000,
    sellPrice: 500,
    emoji: "🍃",
    auctionable: true,
  },
  piedra_lunar: {
    id: "piedra_lunar",
    name: "Piedra Lunar",
    description: "Misteriosa gema oscura como la medianoche que brilla al reflejar la luna para inducir evolución.",
    category: "coleccion",
    rarity: "epico",
    price: 1200,
    sellPrice: 600,
    emoji: "🌙",
    auctionable: true,
  },
  piedra_solar: {
    id: "piedra_solar",
    name: "Piedra Solar",
    description: "Gema ardiente con los colores del atardecer que emana calor solar para inducir evolución.",
    category: "coleccion",
    rarity: "epico",
    price: 1200,
    sellPrice: 600,
    emoji: "☀️",
    auctionable: true,
  },
  huevo_comun: {
    id: "huevo_comun",
    name: "Huevo Común",
    description: "Huevo con manchas verdes que incuba una criatura Común o Poco Común.",
    category: "consumible",
    rarity: "comun",
    price: 1500,
    sellPrice: 750,
    emoji: "🥚",
    auctionable: true,
  },
  huevo_mistico: {
    id: "huevo_mistico",
    name: "Huevo Místico",
    description: "Huevo con aura purpúrea y gran probabilidad de contener una criatura Épica o Rara.",
    category: "consumible",
    rarity: "epico",
    price: 4000,
    sellPrice: 2000,
    emoji: "🔮",
    auctionable: true,
  },
  huevo_legendario: {
    id: "huevo_legendario",
    name: "Huevo Legendario",
    description: "Huevo ancestral radiante con posibilidad de eclosionar una criatura Legendaria.",
    category: "consumible",
    rarity: "legendario",
    price: 12000,
    sellPrice: 6000,
    emoji: "✨",
    auctionable: true,
  },
};

export function isTrainerItem(id: string): boolean {
  return (
    id === "pokeball" ||
    id === "superball" ||
    id === "ultraball" ||
    id === "masterball" ||
    id.startsWith("baya_") ||
    id === "pocion_maxima" ||
    id === "caramelo_raro" ||
    id.startsWith("piedra_") ||
    id.startsWith("huevo_")
  );
}

export function getItemDef(id: string): ItemDef | undefined {
  return ITEMS_REGISTRY[id];
}

export function getAllItems(): ItemDef[] {
  return Object.values(ITEMS_REGISTRY);
}

/** Devuelve la lista compatible con el catálogo original de la tienda */
export function getShopItemsList(): { id: string; name: string; price: number; desc: string }[] {
  return getAllItems()
    .filter((i) => i.price !== undefined && i.price > 0)
    .map((i) => ({
      id: i.id,
      name: `${i.name} ${i.emoji}`,
      price: i.price!,
      desc: i.description,
    }));
}

export function getCollection(id: string): ItemCollection | undefined {
  return COLLECTIONS.find((c) => c.id === id);
}

export function getUserCollectionProgress(
  inv: Record<string, number>,
  collectionId: string,
): { collection: ItemCollection; total: number; owned: number; pct: number; items: { def: ItemDef; count: number }[] } | null {
  const col = getCollection(collectionId);
  if (!col) return null;
  const items = col.itemIds.map((id) => {
    const def = getItemDef(id)!;
    const count = inv[id] ?? 0;
    return { def, count };
  });
  const owned = items.filter((i) => i.count > 0).length;
  const total = items.length;
  const pct = Math.round((owned / total) * 100);
  return { collection: col, total, owned, pct, items };
}

export const COLLECTION_REWARD_AMOUNT = 10000;


export function getItemsByCategory(category: string): ItemDef[] {
  const all = getAllItems().filter((i) => i.price !== undefined && i.price > 0);
  if (category === "todas" || !category) return all;
  if (category === "herramienta") return all.filter((i) => i.category === "herramienta");
  if (category === "consumible") return all.filter((i) => i.category === "consumible");
  if (category === "pesca") return all.filter((i) => i.category === "pesca");
  if (category === "caza") return all.filter((i) => i.category === "caza");
  if (category === "coleccion") return all.filter((i) => i.category === "coleccion");
  if (category === "cosmetico") return all.filter((i) => i.category === "cosmetico");
  return all.filter((i) => i.category === category);
}
